name: opv2v_center_point_lidar_late
root_dir: "/GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/train"
validate_dir: "/GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/validate"
test_dir: "/GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/test"

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 6
  epoches: 50
  eval_freq: 2
  save_freq: 2
  max_cav: &max_cav 5

input_source: ['lidar']
label_type: 'lidar'

comm_range: 70

fusion:
  core_method: 'late' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  dataset: 'opv2v'
  args:
    proj_first: False # early is proj first.

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  # lidar range for each individual cav. Format: xyzxyz minmax
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  anchor_args:
    D: 1
    H: 200
    W: 704
    cav_lidar_range: *cav_lidar
    feature_stride: 2
    h: 1.56
    l: 3.9
    num: 1
    r: &id005
    - 0
    vd: 4
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: VoxelPostprocessor
  dir_args:
    anchor_yaw: *id005
    dir_offset: 0.7853
    num_bins: 1
  gt_range: *cav_lidar
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2

# model related
model:
  core_method: center_point
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: 1
    max_cav: *max_cav
    compression: 0 # compression rate
    backbone_fix: false
    supervise_single: false
    out_size_factor: 2

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      resnet: false
      layer_nums: &layer_nums [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: &num_filters [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      compression: 0
      voxel_size: *voxel_size
    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384 # 128 * 3
    anchor_num: 1

    dir_args:
      anchor_yaw: *id005
      dir_offset: 0.7853
      num_bins: 1

loss:
  args:
    cls_weight: 1.0
    code_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    loc_weight: 2.0
    target_assigner_config:
      box_coder: ResidualCoder
      cav_lidar_range: &id004
      - -140.8
      - -40
      - -3
      - 140.8
      - 40
      - 1
      gaussian_overlap: 0.1
      max_objs: 100
      min_radius: 2
      out_size_factor: 2
      voxel_size: &id001
      - 0.4
      - 0.4
      - 4
  core_method: center_point_loss
      
optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 20]

