comm_range: 200
data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args:
    clip_pc: false
    proj_first: false
  core_method: intermediate
  dataset: opv2v
input_source:
- lidar
label_type: lidar
loss:
  args:
    detection_fix: True
    codebook_weight: 1.0
    cls_weight: 1.0
    code_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    loc_weight: 2.0
    target_assigner_config:
      box_coder: ResidualCoder
      cav_lidar_range: &id004
      - -140.8
      - -40
      - -3
      - 140.8
      - 40
      - 1
      gaussian_overlap: 0.1
      max_objs: 100
      min_radius: 2
      out_size_factor: 2
      voxel_size: &id001
      - 0.4
      - 0.4
      - 4
  core_method: center_point_codebook_loss
lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size:
  - 10
  - 20
model:
  args:
    backbone_fix: True
    anchor_number: 1
    base_bev_backbone:
      compression: 0
      layer_nums: &id002
      - 3
      - 4
      - 5
      layer_strides:
      - 2
      - 2
      - 2
      num_filters: &id003
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      resnet: true
      upsample_strides:
      - 1
      - 2
      - 4
      voxel_size: *id001
    fusion_args:
      channel_compressor:
        k: [256, 256, 256]
        m: 2
      agg_operator:
        feature_dim: 384
        mode: MAX
      downsample_rate: 1
      dropout_rate: 0
      in_channels: 384
      layer_nums: *id002
      multi_scale: true
      n_head: 8
      num_filters: *id003
      only_attention: true
      voxel_size: *id001
    lidar_range: *id004
    max_cav: 5
    out_size_factor: 2
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      grid_size: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          wAIAAAAAAADIAAAAAAAAAAEAAAAAAAAA
      num_features: 64
    shrink_header:
      dim:
      - 256
      input_dim: 384
      kernal_size:
      - 3
      padding:
      - 1
      stride:
      - 1
    supervise_single: true
    voxel_size: *id001
  core_method: center_point_where2comm
name: opv2v_centerpoint_where2comm_codebook_withshrinkhead
noise_setting: !!python/object/apply:collections.OrderedDict
- - - add_noise
    - false
only_vis_ego: true
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.002
postprocess:
  anchor_args:
    D: 1
    H: 200
    W: 704
    cav_lidar_range: *id004
    feature_stride: 2
    h: 1.56
    l: 3.9
    num: 1
    r: &id005
    - 0
    vd: 4
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: VoxelPostprocessor
  dir_args:
    anchor_yaw: *id005
    dir_offset: 0.7853
    num_bins: 1
  gt_range: *id004
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.2
preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id001
  cav_lidar_range: *id004
  core_method: SpVoxelPreprocessor
root_dir: /GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/train
test_dir: /GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/test
train_params:
  batch_size: 4
  epoches: 40
  eval_freq: 2
  max_cav: 5
  save_freq: 2
validate_dir: /GPFS/rhome/yifanlu/OpenCOOD/dataset/OPV2V/validate
yaml_parser: load_point_pillar_params
